name: End-to-end tests

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.18.0-chrome107-ff106-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
